### ISSUE TITLE
A type in SDM630.yml

### ISSUE THREAD

**Issue by i3p14** [samuelphy/energy-meter-logger#1]
Great project! 
I'm new to github so I'm not sure if this the correct way of doing this so please let me know if not.
Just noticed that line 3 for SDM630.yml probably should be changed 
from "Voltage Phase 2 : 4" 
to "Voltage Phase 3 : 4"

**Comment by samuelphy** [comment]
Yes, correct. I'll fix it and commit the change. Thanks!
