### ISSUE TITLE
Compatibility with Python 3.8 

### ISSUE THREAD

**Issue by bikeymouse** [samuelphy/energy-meter-logger#3]
Hi,
First big thanks for this great script that I have used successfully for almost a year now to read the values from a SDM630 meter.
Recently I have migrated this to run in a Docker Container, which use Python 3.8. 

There I first ran into a problem of getting an error because of a depreciated use of:
yaml.load which is considered not to be safe. I have replaced that (lines 32, 70, 182) with
yaml.full_load.

Now that works again. So perhaps good to add this to your code here?

**Comment by samuelphy** [comment]
This issue should now be fixed due to PR #5
