### ISSUE TITLE
Error with Python 3.8: TypeError: '<' not supported between instances of 'dict' and 'dict'

### ISSUE THREAD

**Issue by bikeymouse** [samuelphy/energy-meter-logger#4]
Hi,
I have moved energy-meter-logger.py to Docker, but that uses Python 3.8 which gives the following error, as soon as I use more then 1 meter definition in the meters.yml file:

`Traceback (most recent call last):
File "/app/read_energy_meter.py", line 189, in <module> 
collector = DataCollector(influx_client=client,
File "/app/read_energy_meter.py", line 24, in __init__
 for meter in sorted(self.get_meters()):
TypeError: '<' not supported between instances of 'dict' and 'dict'`

I have very little Python knowledge, but from Google I learned that this is probably because:
[In Python 3, dictionaries are no longer orderable (together with many other types), just use that value as the sorting key](https://stackoverflow.com/questions/55695479/typeerror-not-supported-between-instances-of-dict-and-dict)

Based on this I have tried to change line 24 from:
`for meter in sorted(self.get_meters()):`
To
`for meter in sorted(self.get_meters(),key = lambda meter_yaml: meter_yaml['name']):`

The error is no longer present, but although the script seems to run fine and the log says it reads the values from 2 meters, only the data for 1 meter is actually written to the database.

Does anybody know how to solve this properly?

**Comment by platini2** [comment]
Newer PyYAML needs and extra parameter, you can fix this way.
sed -i "s|new_map = yaml.load(open(self.meter_yaml))|new_map = yaml.load(open(self.meter_yaml), Loader=yaml.FullLoader)|" read_energy_meter.py
sed -i "s|parameters = yaml.load(open(meter['type']))|parameters = yaml.load(open(meter['type']), Loader=yaml.FullLoader)|" read_energy_meter.py
sed -i "s|influx_config = yaml.load(open('influx_config.yml'))|influx_config = yaml.load(open('influx_config.yml'), Loader=yaml.FullLoader)|" read_energy_meter.py

**Comment by samuelphy** [comment]
Also, this issue seems to be fixed by PR #5, although not verified by me. Please reopen if this is not the case.
